-- 0021_subagent_handles.sql — re-queryable subagents (GOALS §3c, plan §3d).
--
-- When a read-only noninteractive subagent (e.g. `explore`) reports back in
-- `normal` mode, its full transcript is persisted here keyed by an opaque
-- handle surfaced to the caller. A follow-up `task(resume_handle=…)`
-- rehydrates the transcript and re-runs the subagent with full knowledge of
-- what it already did. Persist-and-rehydrate (not in-memory retention) so a
-- re-query survives a daemon restart and the history is inspectable. The
-- fixed two-stage `docs` pipeline is excluded — it never reaches this table,
-- so a handle never points at a docs run.
--
-- `transcript_json` is the JSON-serialized `Vec<rig::message::Message>`. The
-- handle is generated by the engine (UUID-derived); `agent` records which
-- subagent it belongs to so a follow-up rebuilds the right factory.

CREATE TABLE subagent_handles (
    handle          TEXT PRIMARY KEY,
    session_id      TEXT NOT NULL
        REFERENCES sessions (session_id) ON DELETE CASCADE,
    agent           TEXT NOT NULL,
    transcript_json TEXT NOT NULL,
    created_at      INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL
);

CREATE INDEX idx_subagent_handles_session ON subagent_handles (session_id);
